
services:
  prairielearn:
    image: prairielearn/prairielearn:latest
    environment:
      HOST_JOBS_DIR: /tmp/directory/for/autograder/jobqueue
    ports:
      - 3000:3000
    volumes:
      - /tmp/directory/for/autograder/jobqueue:/jobs
      - .:/course
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
